version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  web:
    image: kiranbc050/cloudsekproj-web-app:0.0.1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  django-q:
    image: kiranbc050/cloudsekproj-django-q:0.0.1
    command: python manage.py qcluster
    volumes:
      - .:/code
    depends_on:
      - redis
